'use strict';

export default {
  splashBackground : '#454F63',
  gradientOne : '#71c7fe',
  gradientTwo : '#2564d5',
  primary: '#353D4E',
  topBarColor : '#2A2E43',
  topBarColorLight : '#2A2E43',
  primaryTextColor : '#78849E',
  filterTextColor : '#8592AD',
  headingTextColor : '#EDEDED',
  prominentTextColor : '#fff',
  titleTextColor : '#4B5468',
  sectionHeaderText : '#DDE0E7',
  iconBackground : '#F5F5F5',
  backGroundColor : '#353D4E',
  cardColor : '#2A2E43',
  leadTextColor : '#58595b',
  sectionHeaderColor : '#fff',
  lineColor : 'black',
  leadDetailTabViewColor : '#fff',
  buttonColor : '#53DBA7',
  buttonCloseColor : '#78849E',
  buttonColorDisabled : '#adffe0',
  buttonTextColor : '#fff',
  buttonColorLight : 'rgb(147,149,152)',
  selectedTabColor : '#fff',
  unSelectedTabColor : '#f6f6f6',
  bottomBarColor : '#d4d5d6',
  topHeaderSideMenu : '#454F63',
  popupTitleBG : '#3576ea',
  placeHolderText : '#919191',
  selectedFilterColor : '#53DBA7',
  itemColor : '#fff',
  separatorColor : '#EDEDED',
  lightGreyShade : '#97A2BA',
  detailHeadingColor : '#212236',
  detailBodyColor : '#353D4E'
};
